// Managed by the optional Phoniebox installer. Classic AirPlay, shared audio.
general = {
    name = "Phoniebox (%H)";
    output_backend = "pulseaudio";
    dbus_service_bus = "system";
};
sessioncontrol = {
    active_state_timeout = 10.0;
};
metadata = {
    enabled = "yes";
    include_cover_art = "no";
    cover_art_cache_directory = "";
};
